[book]
authors = ["Steven Hé (Sīchàng)"]
language = "en"
multilingual = false
src = "src"
title = "Steven's Notes"

[build]
build-dir = "."

[output.html]
git-repository-url = "https://github.com/SichangHe/notes"

[output.katex]

[preprocessor.katex]
