[book]
authors = ["Steven Hé (Sīchàng)"]
language = "en"
multilingual = false
src = "src"
title = "Steven Hé (Sīchàng)'s Notes"

[build]
build-dir = "html"

[output.html]
git-repository-url = "https://github.com/SichangHe/notes"

[preprocessor.katex]
include-src = true

[preprocessor.toc]
before = ["katex"]
