name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: configure git
      run: |
        git config --global user.name "SichangHe"
        git config --global user.email "sichanghe@users.noreply.github.com"
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Build
      run: mdbook build
    - name: push
      run: |
        git checkout gh-pages
        git add docs
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push -f
