name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: configure git
      run: |
        git config --global user.name "SichangHe"
        git config --global user.email "sichanghe@users.noreply.github.com"
    - name: make bin
      run: |
        mkdir bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Install mdbook
      run: |
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
    - name: Install mdbook-katex
      run: |
        curl -sSL https://github.com/lzanini/mdbook-katex/releases/download/v0.2.10/mdbook-katex-v0.2.10-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
    - name: Build
      run: mdbook build
    - name: push
      run: |
        mv docs docs_new
        git fetch
        git switch gh-pages
        rm -rf docs
        mv docs_new docs
        git add docs
        git commit --allow-empty -m "Deploy $GITHUB_SHA to gh-pages"
        git push -f
