name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: clone down
      run: |
        git config --global user.name "Deploy from CI"
        git config --global user.email ""
        git clone --no-checkout git@github.com:SichangHe/notes.git docs
        cd docs
        git checkout gh-pages
        cd ..
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Build
      run: mdbook build
    - name: push
      run: |
        cd docs
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push origin gh-pages --force
